### ISSUE TITLE
SSH acces issue after upgrade

### ISSUE THREAD

**Issue by GannonTdW** [YunoHost-Apps/gitea_ynh#55]
Hello,

```
# yunohost --version 
yunohost: 
  repo: stable
  version: 11.0.9.13
yunohost-admin: 
  repo: stable
  version: 11.0.10
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```

I have upgrade yunohost Gitea app from 1.17.0\~ynh1 (or   1.16.X\~ynhX ? )  to 1.17.1~ynh1 and yunohost to  11.0.9.13.
I had exactly the same problem described [HERE](https://forum.yunohost.org/t/resolu-probleme-dacces-ssh-gitea/21068/4).
And after the following commands, all is ok.

```
# yunohost service stop gitea
Success! Service 'gitea' stopped
# usermod -d /home/yunohost.app/gitea gitea
# yunohost service start gitea
Success! Service 'gitea' stopped
```

II do not control the bash yunohots functions.
But I suggest adding something like that to the update script.

```bash
if grep -q '/home/gitea' /etc/passwd;then
    yunohost service stop gitea
    usermod -d /home/yunohost.app/gitea gitea
    yunohost service start gitea
fi
```

Or add a message on the README. As you will.
